https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  links:
    - hipchatconnect
  restart: always
  environment:
    DOMAINS: 'hipchat.laurentkempe.com -> http://hipchatconnect:5000'
    STAGE: 'production'
    # STAGE: local
    # FORCE_RENEW: 'true'

hipchatconnect:
  image: laurentkempe/hipchatconnect
  environment:
    BASE_URL: 'https://hipchat.laurentkempe.com'